name: voice_assistant
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  get_it: ^8.0.3
  go_router: ^14.8.0
  hive_flutter: ^1.1.0
  speech_to_text: ^7.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

fonts:
  - family: Ubuntu
    fonts:
      - asset: assets/fonts/ubuntu/Ubuntu-Medium.ttf
        weight: 500
      - asset: assets/fonts/ubuntu/Ubuntu-Regular.ttf
        weight: 400
      - asset: assets/fonts/ubuntu/Ubuntu-Bold.ttf
        weight: 700
      - asset: assets/fonts/ubuntu/Ubuntu-Italic.ttf
        style: italic
